name: Build and deploy to GitHub Pages

on:
    push:
        branches: [ master, main ]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout source
                uses: actions/checkout@v4
            -   name: Checkout articles submodule
                uses: actions/checkout@v4
                with:
                    repository: fmatsos/articles
                    token: ${{ secrets.ARTICLES_TOKEN }}
                    ref: 'main'
                    path: "pages/articles"
            -   name: Check articles
                uses: jtmullen/submodule-branch-check-action@v1
                with:
                    path: "pages/articles"
                    branch: "main"
                    first_parent: true
                    fetch_depth: "50"
                    pass_if_unchanged: true
                    require_head: true
                    disable_progression: true
            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.1'
                    extensions: mbstring, gd, imagick, intl, gettext
            -   name: Build with Cecil
                uses: Cecilapp/Cecil-Action@v3
            -   name: Upload artifact
                uses: actions/upload-pages-artifact@v3
    deploy:
        needs: build
        permissions:
            pages: write
            id-token: write
        concurrency:
            group: pages
            cancel-in-progress: true
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        steps:
            -   name: Deploy to GitHub Pages
                id: deployment
                uses: actions/deploy-pages@v4
