name: Build and deploy to GitHub Pages

on:
    push:
        branches: [ master, main ]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout source
                uses: actions/checkout@v4
            -   name: Update articles to latest on main branch
                run: |
                    git config --file .gitmodules submodule.pages/articles.url https://x-access-token:${{ secrets.ARTICLES_TOKEN }}@github.com/fmatsos/articles.git
                    git submodule sync --recursive
                    git submodule update --init --recursive
            -   name: Pull last articles
                run: |
                    cd pages/articles
                    git checkout main
                    git pull origin main
            -   name: Verify articles update
                run: |
                    git submodule status
            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.1'
                    extensions: mbstring, gd, imagick, intl, gettext
            -   name: Set NodeJs
                uses: actions/setup-node@v4
                with:
                    node-version: 18
            -   name: Build CSS
                run: |
                    npm install && npm run build
            -   name: Build site with Cecil
                uses: Cecilapp/Cecil-Action@v3
                with:
                    args: '-vv --clear-cache --optimize'
            -   name: Upload artifact
                uses: actions/upload-pages-artifact@v3
    deploy:
        needs: build
        permissions:
            pages: write
            id-token: write
        concurrency:
            group: pages
            cancel-in-progress: true
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        steps:
            -   name: Deploy to GitHub Pages
                id: deployment
                uses: actions/deploy-pages@v4
